# -*- coding: utf-8 -*-
"""Pract3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmHuUDmaP1KUOkFdo_ZajTw8OB2ymIMF

Descriptive Statistics - Measures of Central Tendency and variability
Perform the following operations on any open source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the
age groups. Create a list that contains a numeric value for each response to the categorical
variable.
2. Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.
Provide the codes with outputs and explain everything that you do in this step.
"""

import numpy as np

"""now perform mean"""

speed = [10,20,30,40,50]
x = np.mean(speed)
print(x)

x1 = np.median(speed)
print(x)

from scipy import stats
speed1 = [10, 20,20,30,40]
x = stats.mode(speed1)
print(x)

n_num = [1,2,3,4,5]
n = len(n_num)
get_sum = sum(n_num)
mean = get_sum / n
print(mean)

n_num = [1,2,3,4,5]
n = len(n_num)
if n%2 == 0:
  median1 = n_num[n//2]
  median2 = n_num[n//2-1]
  median = (median1+median2)/2
else:
  median = n_num[n//2]
print("Median: " + str(median))

import pandas as pd
df = pd.DataFrame({'A' : ['a', 'b', 'c', 'c', 'a', 'b'],
'B' : [0, 1, 1, 0, 1, 0]}, dtype = "category")
df.dtypes

print(df)
print(df.groupby(['A']). count().reset_index())

data = pd.read_csv(r"/content/sample_data/Iris.csv")

data

data.describe()

print('Data setosa')
setosa = data['Species'] == 'Iris-setosa'
print(data[setosa].describe())

print('Data versicolor')
versicolor = data['Species'] == 'Iris-versicolor'
print(data[versicolor].describe())

print('Data virginica')
virginica = data['Species'] == 'Iris-virginica'
print(data[virginica].describe())