# -*- coding: utf-8 -*-
"""Practical 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101gXuCvuQ8MCzGjf_ChzCKywX55YHdw-

Data Wrangling, I
Perform the following operations using Python on any open source dataset (e.g., data.csv)
1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear
 description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas dataframe.
4. Data Preprocessing: check for missing values in the data using pandas isnull(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables etc.
Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking
the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the
data set. If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.
In addition to the codes and outputs, explain every operation that you do in the above steps and
explain everything that you do to import/read/scrape the data set
"""

pip install pandas

import pandas as pd
import numpy as np

"""Upload CSV to the files->sample_data"""

df = pd.read_csv(r"/content/sample_data/StudentsPerformance.csv")

"""Print the data"""

print(df)

df

df.head(15)

df.isnull()

df.isnull().sum()

df.ndim

print(df.describe())

df.dtypes

df.dropna(axis=1)

y = df.iloc[:, 0:1]
print(y)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

print(df['race/ethnicity'].value_counts())

df_Lunch = pd.get_dummies(df['lunch'])
df_new = pd.concat([df, df_Lunch], axis=1)
print(df_new)

df["writing score"].astype(int)

df = df.dropna()

df

df["writing score"] = df["writing score"].astype(int)

df

df["gender"].replace({"female":0, "male":1}, inplace = True)

df